### PR TITLE
Fat-758: Implement tests for test case C11112

### PR DESCRIPTION
**Pull request by Javokhir12**
# Purpose
* Implement e-2-e automation of test case C11112: Search the "View all" log screen

# Appoach
* Implement tests using `cypress`

# Refs
* https://issues.folio.org/browse/FAT-758

# Screenshots
* Passing Tests
Screenshot (130)

* User story
MicrosoftTeams-image

### CODE REVIEW

**Comment by Javokhir12** [comment]
Hi, @dmitriyfolio, @KyryloBrener and @TetianaParanich. As you can see `User story screenshot` at the top, 
when user search with `Keyword/ID/File name`, matched items should be displayed. 
As you can see in my code my `search term`  hard-coded. Also, imported `jobLogs` are dynamic and can change anytime.
My question is that how can we test this cases in general? Should we stub `request` to `jobLogs`? 
Your advice are highly appreciated.

**Comment by dmitriyfolio** [comment]
>

**Comment by Javokhir12** [comment]
> > 
> 
> I think you don't need to use stub in smoke tests. Do you have ability to import small package of test data , grab all required details about data and import job and assert jobLog based on it?

@dmitriyfolio, I did import my own test files but I thought it should not be hard-coded values.

**Comment by dmitriyfolio** [comment]
>  I did import my own test files but I thought it should not be hard-coded values

it should be implemented into test preconditions as cypress/interactors steps.

**Comment by Javokhir12** [comment]
> > I did import my own test files but I thought it should not be hard-coded values
> 
> it should be implemented into test preconditions as cypress/interactors steps. It's nice to have Fabric which provides you "default" import content with unique and actual data. You just request in test new data to import from this Fabric and initialize import at the beginning of your test.

@dmitriyfolio, Could you please provide example since I am new to `stripes-tests`?

**Comment by dmitriyfolio** [comment]
> > > I did import my own test files but I thought it should not be hard-coded values
> > 
> > 
> > it should be implemented into test preconditions as cypress/interactors steps. It's nice to have Fabric which provides you "default" import content with unique and actual data. You just request in test new data to import from this Fabric and initialize import at the beginning of your test.
> 
> @dmitriyfolio, Could you please provide example since I am new to `stripes-tests`?

Could you enumerate not clear to you points?

**Comment by dmitriyfolio** [comment]
as I see this PR was closed by me by mistake. I try to revert it into open state.

**Comment by Javokhir12** [comment]
> as I see this PR was closed by me by mistake. I try to revert it into open state. @Javokhir12 , please check from your side

Hi Dmitriy! no problem.

**Comment by MaksimTerekhov** [comment]
> Hi, @dmitriyfolio, @KyryloBrener and @TetianaParanich. As you can see `User story screenshot` at the top, when user search with `Keyword/ID/File name`, matched items should be displayed. As you can see in my code my `search term` hard-coded. Also, imported `jobLogs` are dynamic and can change anytime. My question is that how can we test this cases in general? Should we stub `request` to `jobLogs`? Your advice are highly appreciated.

As I see we have a problem in case without imports on current environment.
I suggest before this test case make a test for import file. May be we have this in our test rail. Actually I don't know
And you can add action after all tests in this file 
`after( () => { just_delete_imported_item_here } )`
Or we can put a third test on deleting check

Eventually in one file we will have 3 tests:
 - Import
 - Search
 - Delete

And it solves your problem with hardcode. When you import file from test you will know ID, name and other things

@dmitriyfolio, @KyryloBrener what do you think? May be you have other suggestions

**Comment by dmitriyfolio** [comment]
> As I see we have a problem in case without imports on current environment.

could you provide more details about this problem?

**Comment by MaksimTerekhov** [comment]
> > As I see we have a problem in case without imports on current environment.
> 
> could you provide more details about this problem?

For example on snapshot we have 1 result

image

For dev env we have 0 result

image

**Comment by dmitriyfolio** [comment]
I think tests should not be related. And we should try to clear generated test data after all test steps. Generation and clearing should be implemented through api requests ideally.
 Additionally I should remind that our test envs are clearing from new test data on daily basis.

**Pull request closed without merging**
