### PR TITLE
STCOM-785: interactors update: accordion

### PR DESCRIPTION
**Pull request by cowboyd**
Motivation
-----------

Upgrade the Accordion interactor to the new bigtest interactor syntax and make it available for consumption by any test suite. You can see this in action in https://github.com/folio-org/stripes-components/pull/1455

Approach
----------

This replaces the need for custom `expect` syntax by using smart filters on the accordion interactor. You can aski if an accordion is `closed`, `focused`, what it's `contentHeight` is and so forth.

Rather than add the actions to do things like `focusNext()` and `focusPrevious()` to the interactor itself, I instead opted to implement a `Keyboard` interactor which has actions for pressing the navigation keys like `Keyboard.arrowUp()` and `Keyboard.arrowDown()` since that's more akin to what the actual user is doing.

### CODE REVIEW

**Comment by cowboyd** [comment]
@JohnC-80 How should we handle documentation for these interactors? In the Readme?

**Comment by JohnC-80** [comment]
@cowboyd maybe a listing within the readme with pages for individual components? would these warrant a page-per or just a section of a page? The end result will need to be included somehow (linked at least) in the component's documentation within stripes-components.

**Review by JohnC-80 — APPROVED** [review]

**Comment by cowboyd** [comment]
@JohnC-80 can you merge this one down? It's ready to go and includes a start on the documentation https://github.com/cowboyd/stripes-testing/blob/accordion-interactor/doc/interactors.md

**Comment by cowboyd** [comment]
@JohnC-80 can you merge this one down? It's ready to go and includes a start on the documentation

**Pull request merged**
