### PR TITLE
FAT-899: Spike: learn how to build UI e-2-e test with Cypress+BigTest

### PR DESCRIPTION
**Pull request by BogdanDenis**
## Description
Add Cypress tests for following cases:

- quickMARC
    - Derive a new MARC bib record
    - Add a new MARC tag that it adds a default $a
    - Editing a 006/00 value
- eHoldings
    - Edit Provider record (proxy)
    - Searching Providers
- Notes
    - Create a note
    - Edit a note
    - View a note
    - Assign/Unassign a note

## Open questions
- Is there a way to wait for an element to appear? Using constant timeouts doesn't seem to be the right way to do this.

### CODE REVIEW

**Comment by cowboyd** [comment]
> Is there a way to wait for an element to appear? Using constant timeouts doesn't seem to be the right way to do this.

@BogdanDenis interactors implicitly wait for the element to appear before executing any actions on them, so if the element cannot be found, it is because it either does not exist, or it is hidden from view. For example:

```js
cy.do(Button("Submit").click());
```

will wait until the button is both in the DOM _and_ visible before executing the click.

**Comment by cowboyd** [comment]
I was trying to run the tests locally, but couldn't get them working. Whenever I tried to run the `yarn cypress:snapshot` command, it failed with the following error: Is there another step that I need to take on my local environment?

```
  Running:  checkout/checkout.basic.spec.js                                                 (2 of 6)


  Check Out
    1) "before each" hook for "Basic flow"
    2) "after all" hook for "Basic flow"


  0 passing (9s)
  2 failing

  1) Check Out
       "before each" hook for "Basic flow":
     CypressError: `cy.request()` failed on:

https://folio-snapshot.dev.folio.org/undefined/bl-users/login?limit=1000&query=cql.allRecords%3D1

The response we received from your web server was:

  > 405: Method Not Allowed

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: https://folio-snapshot.dev.folio.org/undefined/bl-users/login?limit=1000&query=cql.allRecords%3D1
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/6.9.1 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 44
}
Body: {"username":"diku_admin","password":"admin"}

-----------------------------------------------------------

The response we got was:

Status: 405 - Method Not Allowed
Headers: {
  "date": "Wed, 23 Jun 2021 15:31:05 GMT",
  "content-type": "text/html; charset=utf-8",
  "content-length": "559",
  "connection": "keep-alive",
  "server": "nginx/1.20.1"
}
Body: <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Check Out`
      at https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:160310:21
      at tryCatcher (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:10765:23)
      at Promise._settlePromiseFromHandler (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8700:31)
      at Promise._settlePromise (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8757:18)
      at Promise._settlePromise0 (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8802:10)
      at Promise._settlePromises (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8882:18)
      at _drainQueueStep (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5472:12)
      at _drainQueue (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5465:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5481:5)
      at Async.drainQueues (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5351:14)
  From Your Spec Code:
      at Context.eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress/support/index.js:32625:6)

  2) Check Out
       "after all" hook for "Basic flow":
     TypeError: Cannot read property 'name' of undefined

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Check Out`
      at Context.eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress/support/index.js:32590:74)
```

**Comment by BogdanDenis** [comment]
> > Is there a way to wait for an element to appear? Using constant timeouts doesn't seem to be the right way to do this.
> 
> @BogdanDenis interactors implicitly wait for the element to appear before executing any actions on them, so if the element cannot be found, it is because it either does not exist, or it is hidden from view. For example:
> 
> ```js
> cy.do(Button("Submit").click());
> ```
> 
> will wait until the button is both in the DOM _and_ visible before executing the click.

Thanks, I'll try this method

**Comment by BogdanDenis** [comment]
> I was trying to run the tests locally, but couldn't get them working. Whenever I tried to run the `yarn cypress:snapshot` command, it failed with the following error: Is there another step that I need to take on my local environment?
> 
> ```
>   Running:  checkout/checkout.basic.spec.js                                                 (2 of 6)
> 
> 
>   Check Out
>     1) "before each" hook for "Basic flow"
>     2) "after all" hook for "Basic flow"
> 
> 
>   0 passing (9s)
>   2 failing
> 
>   1) Check Out
>        "before each" hook for "Basic flow":
>      CypressError: `cy.request()` failed on:
> 
> https://folio-snapshot.dev.folio.org/undefined/bl-users/login?limit=1000&query=cql.allRecords%3D1
> 
> The response we received from your web server was:
> 
>   > 405: Method Not Allowed
> 
> This was considered a failure because the status code was not `2xx` or `3xx`.
> 
> If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
> 
> -----------------------------------------------------------
> 
> The request we sent was:
> 
> Method: POST
> URL: https://folio-snapshot.dev.folio.org/undefined/bl-users/login?limit=1000&query=cql.allRecords%3D1
> Headers: {
>   "Connection": "keep-alive",
>   "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/6.9.1 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36",
>   "accept": "*/*",
>   "accept-encoding": "gzip, deflate",
>   "content-type": "application/json",
>   "content-length": 44
> }
> Body: {"username":"diku_admin","password":"admin"}
> 
> -----------------------------------------------------------
> 
> The response we got was:
> 
> Status: 405 - Method Not Allowed
> Headers: {
>   "date": "Wed, 23 Jun 2021 15:31:05 GMT",
>   "content-type": "text/html; charset=utf-8",
>   "content-length": "559",
>   "connection": "keep-alive",
>   "server": "nginx/1.20.1"
> }
> Body: <html>
> <head><title>405 Not Allowed</title></head>
> <body>
> <center><h1>405 Not Allowed</h1></center>
> <hr><center>nginx/1.20.1</center>
> </body>
> </html>
> 
> 
> 
> 
> 
> 
> 
> https://on.cypress.io/request
> 
> Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Check Out`
>       at https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:160310:21
>       at tryCatcher (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:10765:23)
>       at Promise._settlePromiseFromHandler (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8700:31)
>       at Promise._settlePromise (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8757:18)
>       at Promise._settlePromise0 (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8802:10)
>       at Promise._settlePromises (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8882:18)
>       at _drainQueueStep (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5472:12)
>       at _drainQueue (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5465:9)
>       at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5481:5)
>       at Async.drainQueues (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5351:14)
>   From Your Spec Code:
>       at Context.eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress/support/index.js:32625:6)
> 
>   2) Check Out
>        "after all" hook for "Basic flow":
>      TypeError: Cannot read property 'name' of undefined
> 
> Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Check Out`
>       at Context.eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress/support/index.js:32590:74)
> ```

This should be working out of the box. But for some reason you have `undefined` as part of the requested url. Let me see if I can reproduce this

**Comment by BogdanDenis** [comment]
@cowboyd turns out you actually need to specify `CYPRESS_OKAPI_HOST` env variable if you want to point cypress to snapshot or other env
```
export CYPRESS_OKAPI_HOST=https://folio-snapshot-okapi.dev.folio.org && yarn run test:cypress:snapshot
```

**Comment by cowboyd** [comment]
> @cowboyd turns out you actually need to specify `CYPRESS_OKAPI_HOST` env variable if you want to point cypress to snapshot or other env

@BogdanDenis Thanks, I'll give this a try.

**Comment by wKich** [comment]
@BogdanDenis, hi there. I tried to define `CYPRESS_OKAPI_HOST` as you described but got 404 error instead:
```
Check In
    1) "before each" hook for "Basic flow"
    2) "after all" hook for "Basic flow"


  0 passing (7s)
  2 failing

  1) Check In
       "before each" hook for "Basic flow":
     CypressError: `cy.request()` failed on:

https://folio-snapshot-okapi.dev.folio.org/bl-users/login?limit=1000&query=cql.allRecords%3D1

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: https://folio-snapshot-okapi.dev.folio.org/bl-users/login?limit=1000&query=cql.allRecords%3D1
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/6.9.1 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 44
}
Body: {"username":"diku_admin","password":"admin"}

-----------------------------------------------------------

The response we got was:

Status: 404 - Not Found
Headers: {
  "date": "Tue, 29 Jun 2021 06:32:25 GMT",
  "content-type": "text/plain",
  "content-length": "72",
  "connection": "keep-alive",
  "vary": "origin"
}
Body: No suitable module found for path /bl-users/login for tenant supertenant


https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Check In`
      at https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:160310:21
      at tryCatcher (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:10765:23)
      at Promise._settlePromiseFromHandler (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8700:31)
      at Promise._settlePromise (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8757:18)
      at Promise._settlePromise0 (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8802:10)
      at Promise._settlePromises (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:8882:18)
      at _drainQueueStep (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5472:12)
      at _drainQueue (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5465:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5481:5)
      at Async.drainQueues (https://folio-snapshot.dev.folio.org/__cypress/runner/cypress_runner.js:5351:14)
  From Your Spec Code:
      at Context.eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress/support/index.js:1684:6)

  2) Check In
       "after all" hook for "Basic flow":
     TypeError: Cannot read property 'name' of undefined

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Check In`
      at Context.eval (https://folio-snapshot.dev.folio.org/__cypress/tests?p=cypress/support/index.js:1649:74)
```

**Comment by wKich** [comment]
Looks like backend doesn't have some data. Is there any other staging URL?

**Comment by wKich** [comment]
And now when I got tests to work, I'm getting 500
```
The response we got was:

Status: 500 - Internal Server Error
Headers: {
  "date": "Tue, 29 Jun 2021 08:39:06 GMT",
  "content-type": "text/plain",
  "content-length": "206",
  "connection": "keep-alive",
  "vary": "origin",
  "x-okapi-trace": "POST mod-authtoken-2.9.0-SNAPSHOT.91 http://10.36.1.212:9178/inventory/instances.. : 202 12900us"
}
Body: proxyClient failure: mod-inventory-17.1.0-SNAPSHOT.391 http://10.36.1.212:9141: finishConnect(..) failed: Connection refused: /10.36.1.212:9141: POST /inventory/instances?limit=1000&query=cql.allRecords%3D1
```

**Comment by BogdanDenis** [comment]
> And now when I got tests to work, I'm getting 500
> 
> ```
> The response we got was:
> 
> Status: 500 - Internal Server Error
> Headers: {
>   "date": "Tue, 29 Jun 2021 08:39:06 GMT",
>   "content-type": "text/plain",
>   "content-length": "206",
>   "connection": "keep-alive",
>   "vary": "origin",
>   "x-okapi-trace": "POST mod-authtoken-2.9.0-SNAPSHOT.91 http://10.36.1.212:9178/inventory/instances.. : 202 12900us"
> }
> Body: proxyClient failure: mod-inventory-17.1.0-SNAPSHOT.391 http://10.36.1.212:9141: finishConnect(..) failed: Connection refused: /10.36.1.212:9141: POST /inventory/instances?limit=1000&query=cql.allRecords%3D1
> ```

You are right about the `CYPRESS_OKAPI_TENANT` env variable.
As for other envs - you can use https://bugfest-iris.folio.ebsco.com/

**Comment by BogdanDenis** [comment]
> And now when I got tests to work, I'm getting 500
> 
> ```
> The response we got was:
> 
> Status: 500 - Internal Server Error
> Headers: {
>   "date": "Tue, 29 Jun 2021 08:39:06 GMT",
>   "content-type": "text/plain",
>   "content-length": "206",
>   "connection": "keep-alive",
>   "vary": "origin",
>   "x-okapi-trace": "POST mod-authtoken-2.9.0-SNAPSHOT.91 http://10.36.1.212:9178/inventory/instances.. : 202 12900us"
> }
> Body: proxyClient failure: mod-inventory-17.1.0-SNAPSHOT.391 http://10.36.1.212:9141: finishConnect(..) failed: Connection refused: /10.36.1.212:9141: POST /inventory/instances?limit=1000&query=cql.allRecords%3D1
> ```

Sorry, that won't work unless you change used login and password locally because bugfest-iris uses different credentials and tenant
There's also https://folio-testing.dev.folio.org/ - it has the same tenant and credentials as snapshot

**Comment by wKich** [comment]
@BogdanDenis thanks for reply. I'll try different endpoint. But I didn't understand about credentials, what I have to do to fix 500s?

Btw, I start migrating tests from cypress API to using interactors. Could take a brief look to #112

**Comment by BogdanDenis** [comment]
@wKich There's some issues on the backend side on snapshot environment so that's why you're getting 500 errors. But that's causes just the Inventory app tests to fail. eHoldings app tests should be working correctly.
Regarding credentials - bugfest-iris env has different admin credentials so tests won't work there either

**Review by Vladyslav-Velytskyi — APPROVED** [review]

**Review by mariiaschv — APPROVED** [review]

**Pull request merged**
