### PR TITLE
Upgrade interactors to 1.0.0 rc1

### PR DESCRIPTION
**Pull request by wKich**
I can't commit directly to branch https://github.com/folio-org/stripes-testing/pull/146

### CODE REVIEW

**Review by JohnC-80 — APPROVED** [review]

**Comment by cowboyd** [comment]
@JohnC-80 I'll leave it to you to merge this, since it will need to be coordinated with the similar PR to stripes-components

**Comment by JohnC-80** [comment]
Ok @cowboyd

**Comment by cowboyd** [comment]
@JohnC-80 also, what is the incompatibility with the main branch?

**Comment by JohnC-80** [comment]
@cowboyd I'm not sure there are any - this could totally be made against master... the axetest-update branch just had further improvement of the axe testing utility - so it was out along side the activity in the interactors folder.

**Comment by cowboyd** [comment]
@wKich I updated the base to `master`, can you have a look at the conflicts?

**Comment by wKich** [comment]
@cowboyd done

**Pull request merged**
